version: "2"
services:
  sbt:
    image: williamyeh/sbt
    extends:
      service: src
    volumes:
      - ~/.ivy2/cache:/root/.ivy2/cache
      - ~/.sbt:/root/.sbt
  src:
    image: scratch
    dns: 8.8.8.8
    volumes:
      - ../../../:/test-objects
    working_dir: /test-objects